# -*- coding: utf-8 -*-
"""menu_recommendation_lstm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fN6HZn1DsjWaS2vzDMqtsfjDkHsWSMaz
"""

from collections import Counter
import torch.nn as nn
import torch
import numpy as np
import torch.optim as optim

menu = '''
Fri L 12 빵 간식
Fri D 19 돈까스 일식
Sat L 13 고기 고기
Sat D 25 치킨 치킨
Sun L 12 감자탕 한식
Sun D 20 햄버거 햄버거
Mon L 12 삼김 간식
Mon D 20 치킨 치킨
Tue L 12 돈까스 일식
Tue D 21 치킨 치킨
Wed L X X X
Wed D 18 고기 고기
Thu L X X X
Thu D 18 햄버거 햄버거
Fri L 14 막국수 한식
Fri D 21 라면 분식
Sat L 14 칼국수 한식
Sat D 20 휴게소 간식
Sun L 14 라면 분식
Sun D 22 사케동 일식
Mon L 14 햄버거 햄버거
Mon D 19 칼국수 한식
Tue L 12 더랩 간식
Tue D 17 치킨 치킨
Wed L 14 머그 간식
Wed D 18 중국집 중식
Thu L 13 짜글이 한식
Thu D 19 치킨 치킨
Thu N 22 딸기스무디 간식
Fri L 14 육회비빔밥 한식
Fri D 22 피자 피자
Sat L 15 김치찜 한식
Sat D 21 치킨 치킨
Sat N 22 딸쿠스 간식
Sun L 14 불닭 분식
Sun D 21 햄버거 햄버거
Mon L 14 머그 간식
Mon D 20 엽떡 분식
Tue L 12 머그 간식
Tue D 17 롯데리아 간식
Tue N 22 핫도그 간식
Wed L 12 더랩 간식
'''

a = menu.split()

without_spec = []

for i, word in enumerate(a):
    if i % 5 != 3:
        without_spec.append(word)
    else:
        pass

devided = []
label = []
for i, word in enumerate(without_spec):
    if i % 4 == 3:
        if i in {3, 7}:
            pass
        else:
            devided.append(without_spec[i-11:i])
            label.append(without_spec[i])


words_count = Counter(without_spec)
vocab = sorted(words_count, key = words_count.get, reverse = True)


word2idx = {}

word2idx['<pad>'] = 0
word2idx['<unk>'] = 1

for index, word in enumerate(vocab):
  word2idx[str(word)] = int(index+2)


converted2idx = []
label2idx = []

for chunk in devided:
    idx = []
    for word in chunk:
        idx.append(word2idx[word])
    converted2idx.append(idx)

for word in label:
    label2idx.append(word2idx[word])


idx2label = {v: k for k, v in word2idx.items()}


class POSTagger2(nn.Module):
  def __init__(self, vocab_size, embedding_dim, hidden_dim, output_dim, num_layers):
    super(POSTagger2, self).__init__()
    self.embedding = nn.Embedding(vocab_size, embedding_dim)
    self.lstm = nn.LSTM(embedding_dim, hidden_dim, num_layers=num_layers, batch_first=True, bidirectional=False)
    self.fc = nn.Linear(hidden_dim, output_dim)

  def forward(self, x):
    embedded = self.embedding(x)
    _, (h_n, _) = self.lstm(embedded)
    final_hidden_state = h_n[-1, :, :]
    logits = self.fc(final_hidden_state)
    return logits

X_train_tensor = torch.tensor(converted2idx, dtype=torch.long)
y_train_tensor = torch.tensor(label2idx, dtype=torch.long)

train_dataset = torch.utils.data.TensorDataset(X_train_tensor, y_train_tensor)
train_dataloader = torch.utils.data.DataLoader(train_dataset, shuffle=True, batch_size=1)

embedding_dim = 16
hidden_dim = 32
output_dim = len(word2idx)
learning_rate = 0.2
num_epochs = 500
num_layers = 2
vocab_size = len(word2idx)

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
print(device)

model = POSTagger2(vocab_size, embedding_dim, hidden_dim, output_dim, num_layers)
model.to(device)

criterion = nn.CrossEntropyLoss(ignore_index=0)
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

def accuracy(logits, labels, ignore_index=0):
  predicted = torch.argmax(logits, dim=1)
  correct = (predicted == labels).sum().item()
  total = len(labels)

  accuracy = correct/total

  return accuracy

best_train_loss = float('inf')

for epoch in range(num_epochs):

  train_loss = 0
  train_correct = 0
  train_total = 0

  model.train()

  for batch_X, batch_y in train_dataloader:
    batch_X, batch_y = batch_X.to(device), batch_y.to(device)
    logits = model(batch_X)

    loss = criterion(logits.view(-1, output_dim), batch_y.view(-1))

    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    train_loss += loss.item()
    train_correct += accuracy(logits.view(-1, output_dim), batch_y.view(-1)) * batch_y.size(0)
    train_total += batch_y.size(0)

  train_accuracy = train_correct / train_total
  train_loss /= len(train_dataloader)

  if epoch % 50 ==49:
      print(f'Epoch {epoch+1}\nloss: {train_loss}, accuracy: {train_accuracy}')

      if train_loss < best_train_loss:
          print(f'Train loss improved from {best_train_loss:.4f} to {train_loss:.4f}. 체크포인트를 저장합니다.')
          best_train_loss = train_loss
          torch.save(model.state_dict(), 'best_model_checkpoint.pth')

model.load_state_dict(torch.load('best_model_checkpoint.pth'))

model.to(device)

user_input = str(input('Date L/D Hour Type x2 + Date L/D Hour: '))

tokenized = user_input.split()

indexed_input_list = []

for word in tokenized:
  try:
    indexed_input_list.append(word2idx[word])
  except KeyError:
    indexed_input_list.append(word2idx['<unk>'])

padded_tensor = torch.tensor(indexed_input_list, dtype=torch.long).unsqueeze(0)

with torch.no_grad():
  padded_tensor = padded_tensor.to(device)
  user_logits = model(padded_tensor)

user_predicted = torch.argmax(user_logits, dim=1).squeeze().cpu().numpy()

to_label = [idx2label[user_predicted.item()]]

print(to_label)