# -*- coding: utf-8 -*-
"""menu_recommendation_lstm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fN6HZn1DsjWaS2vzDMqtsfjDkHsWSMaz
"""

from collections import Counter
import torch.nn as nn
import torch
import numpy as np
import torch.optim as optim

with open('menu.txt', 'r') as f:
    menu = f.read()

class PreprocessMenu():
    def __init__(self, menu):
        a = menu.split()

        without_spec = []

        for i, word in enumerate(a):
            if i % 5 != 3:
                without_spec.append(word)
            else:
                pass

        devided = []
        label = []
        for i, word in enumerate(without_spec):
            if i % 4 == 3:
                if i in {3, 7}:
                    pass
                else:
                    devided.append(without_spec[i-11:i])
                    label.append(without_spec[i])


        words_count = Counter(without_spec)
        vocab = sorted(words_count, key = words_count.get, reverse = True)


        word2idx = {}

        word2idx['<pad>'] = 0
        word2idx['<unk>'] = 1

        for index, word in enumerate(vocab):
            word2idx[str(word)] = int(index+2)


        converted2idx = []
        label2idx = []

        for chunk in devided:
            idx = []
            for word in chunk:
                idx.append(word2idx[word])
            converted2idx.append(idx)

        for word in label:
            label2idx.append(word2idx[word])


        idx2word = {v: k for k, v in word2idx.items()}

        X_train_tensor = torch.tensor(converted2idx, dtype=torch.long)
        y_train_tensor = torch.tensor(label2idx, dtype=torch.long)

        train_dataset = torch.utils.data.TensorDataset(X_train_tensor, y_train_tensor)
        train_dataloader = torch.utils.data.DataLoader(train_dataset, shuffle=True, batch_size=1)

        self.menu = train_dataloader
        self.word2idx = word2idx
        self.idx2word = idx2word

    @property
    def menu(self):
        return self.__menu

    @property
    def word2idx(self):
        return self.__word2idx

    @property
    def idx2word(self):
        return self.__idx2word

    @menu.setter
    def menu(self, train_dataloader):
        self.__menu = train_dataloader

    @word2idx.setter
    def word2idx(self, word2idx):
        self.__word2idx = word2idx

    @idx2word.setter
    def idx2word(self, idx2word):
        self.__idx2word = idx2word



data = PreprocessMenu(menu)

class MenuRecommend(nn.Module):
    def __init__(self, vocab_size, embedding_dim, hidden_dim, output_dim, num_layers):
        super(MenuRecommend, self).__init__()
        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        self.lstm = nn.LSTM(embedding_dim, hidden_dim, num_layers=num_layers, batch_first=True, bidirectional=False)
        self.fc = nn.Linear(hidden_dim, output_dim)

    def forward(self, x):
        embedded = self.embedding(x)
        _, (h_n, _) = self.lstm(embedded)
        final_hidden_state = h_n[-1, :, :]
        logits = self.fc(final_hidden_state)
        return logits

class ModelTraining(MenuRecommend):
    def __init__(self, data):
        embedding_dim = 16
        hidden_dim = 32
        output_dim = len(data.word2idx)
        learning_rate = 0.2
        num_epochs = 300
        num_layers = 2
        vocab_size = len(data.word2idx)

        device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
        print(device)

        super().__init__(vocab_size, embedding_dim, hidden_dim, output_dim, num_layers)
        self.to(device)

        criterion = nn.CrossEntropyLoss(ignore_index=0)
        optimizer = optim.Adam(self.parameters(), lr=learning_rate)

        best_train_loss = float('inf')

        while True:

            for epoch in range(num_epochs):
                self.train()
                epoch_loss = 0
                epoch_correct = 0
                total_samples = 0

                for batch_X, batch_y in data.menu:
                    batch_X, batch_y = batch_X.to(device), batch_y.to(device)
                
                    optimizer.zero_grad()
                    logits = self(batch_X)
                    loss = criterion(logits, batch_y)
                    loss.backward()
                    optimizer.step()

                    epoch_loss += loss.item()
                
                    predicted = torch.argmax(logits, dim=1)
                    epoch_correct += (predicted == batch_y).sum().item()
                    total_samples += batch_y.size(0)

                avg_loss = epoch_loss / len(data.menu)
                avg_accuracy = epoch_correct / total_samples

                if (epoch + 1) % 50 == 0:
                    print(f'Epoch {epoch+1} | Loss: {avg_loss:.4f} | Accuracy: {avg_accuracy:.4f}')
                
                    if avg_loss < best_train_loss:
                        best_train_loss = avg_loss
                        torch.save(self.state_dict(), 'best_model_checkpoint.pth')
                        print("Checkpoint saved.")

            if best_train_loss < 1:
                break

        self.device = device

    @property
    def device(self):
        return self.__device

    @device.setter
    def device(self, device):
        self.__device = device

trained = ModelTraining(data)

class ModelPrediction():
    def __init__(self, trained, data):

        self.model = trained
        self.data = data
        
        self.model.load_state_dict(torch.load('best_model_checkpoint.pth'))
        self.model.to(self.model.device)

        while True:
            user_input = input("Date L/D Hour Type x2 + Date L/D Hour (enter 'quit' to quit): ")

            if user_input.lower() == 'quit':
                print('Have a good meal!')
                break

            tokenized = user_input.split()
            indexed_input_list = []

            for word in tokenized:
                if word in self.data.word2idx:
                    indexed_input_list.append(self.data.word2idx[word])
                else:
                    indexed_input_list.append(self.data.word2idx['<unk>'])

            if not indexed_input_list:
                continue

            padded_tensor = torch.tensor(indexed_input_list, dtype=torch.long).unsqueeze(0)

            with torch.no_grad():
                padded_tensor = padded_tensor.to(self.model.device)
                user_logits = self.model(padded_tensor)

            user_predicted = torch.argmax(user_logits, dim=1).item()
            to_label = self.data.idx2word[user_predicted]

            print(f"Recommended: {to_label}")


prediction = ModelPrediction(trained, data)